# Generated by Django 5.0.2 on 2024-03-03 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=65)),
                ('descricao', models.TextField(max_length=165)),
                ('slug', models.SlugField()),
                ('tempo_preparo', models.IntegerField()),
                ('tempo_preparo_unidade', models.CharField(max_length=65)),
                ('qtd_porcoes', models.IntegerField()),
                ('qtd_porcoes_unidade', models.CharField(max_length=65)),
                ('modo_preparo', models.TextField()),
                ('modo_preparo_e_html', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('publicada', models.BooleanField(default=False)),
                ('imagem_cover', models.ImageField(upload_to='receitas/covers/%Y/%m/%d/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.categoria')),
            ],
        ),
    ]
