# Generated by Django 5.0.2 on 2024-03-03 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='imagem_cover',
            field=models.ImageField(blank=True, default='', upload_to='receitas/covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='slug',
            field=models.SlugField(max_length=65, unique=True),
        ),
    ]
